spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store_users
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379

grpc:
  client:
    auth-service:
      address: 'static://127.0.0.1:9090'
      negotiationType: plaintext
