apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: online-store
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres_pass"
  REDIS_PASSWORD: "redis_pass"
  INTERNAL_SECRET: "X2mP5vQ8nT3wL6jY9zC2bF5dG8hJ1kN4pS7vX0"
